### ISSUE TITLE
docker使用指南

### ISSUE THREAD

**Issue by lclgo** [lclgo/lclgo.github.io#28]
[docker使用指南](https://yeasy.gitbook.io/docker_practice/)

## 简单命令

```bash
docker run -it -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /docker-run:/run:rw c7-systemd /sbin/init
docker run -it -v /docker-run:/run:rw docker-test /sbin/init
```

```bash
docker import oesystemd.tar.gz oesystemd:1
```

```bash
docker export ID -o oesystemd.tar.gz
```

```bash
docker load -i openeuler-22.03-lts:latest.tar.gz
```
r
## 修改Dockerfile将systemd作为docker的一号进程

```shell
FROM openeuler-22.03-lts:latest
RUN yum install -y systemd
CMD ["/sbin/init"]
```
执行`docker build -t docker-systemd .`构建容器镜像。

**Comment by lclgo** [comment]
## containerd使用指南

### containerd配置文件

#### 镜像仓库

containerd支持两种镜像仓库配置：
1. 配置config.toml的registry mirrors
2. 配置certs.d（1.5.0及以上版本支持：https://github.com/containerd/containerd/commits/b0b6d9aa03ccf903f9bf1a9bc80ea2eecb0b22e9)

方法1配置分两种，旧版本支持的配置为：
```toml
[plugins]
  [plugins.cri]
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://mirror.ccs.tencentyun.com"]
        [plugins.cri.registry.mirrors."ccr.ccs.tencentyun.com"]
          endpoint = ["http://127.0.0.1:65001"]
```
新版本的配置为：
```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://mirror.ccs.tencentyun.com"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ccr.ccs.tencentyun.com"]
      endpoint = ["http://127.0.0.1:65001"]
```
两种配置方法不能混用，可以通过`containerd config dump | grep XXX`确认是否配置成功。

方法2配置，修改`/etc/containerd/config.toml`：
```toml
# explicitly use v2 config format
version = 2
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/certs.d"
```
添加：`/etc/containerd/certs.d/docker.io/hosts.toml`，内容如下：
```toml
server = "https://index.docker.io"

[host."http://127.0.0.1:4001"]
capabilities = ["pull", "resolve"]

[host."http://127.0.0.1:4001".header]
X-Dragonfly-Registry = "https://index.docker.io"
```
方法2配置只需要在修改config.toml时候重启一次containerd，后续在certs.d中修改配置无需重启containerd
